
# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "thebattlepass/"
  publish = "thebattlepass/build"


[[redirects]]
  from = "/api/*"
  to = "https://i1os4xxzw4.execute-api.us-east-2.amazonaws.com/prod"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200