
# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "thebattlepass/"
  publish = "thebattlepass/build"

[[redirects]]
  from = "https://fort-friend.com/*"
  to = "https://www.thebattlepass.com/:splat"
  status = 301
  foce = true

[[redirects]]
  from = "https://www.fort-friend.com/*"
  to = "https://www.thebattlepass.com/:splat"
  status = 301
  foce = true

[[redirects]]
  from = "/api/*"
  to = "https://i1os4xxzw4.execute-api.us-east-2.amazonaws.com/prod/:splat"
  status = 200
  force = true
  signed ="REACT_APP_API_SECRET"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200